# Generated by Django 6.0 on 2026-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('specialty', models.CharField(max_length=100, verbose_name='Спеціалізація')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
                ('website', models.URLField(blank=True, verbose_name='Вебсайт')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
            ],
        ),
    ]
